type User {
  username: String!
  favoriteGenre: String!
  id: ID!
}

type Token {
  value: String!
}

type Author {
    name: String!
    born: Int
    id: ID!
}

type Book {
    title: String!
    published: Int!
    author: Author!
    genres: [String!]!
    id: ID!
}

type Query {
    me: User
    bookCount: Int!
    authorCount: Int!
    allBooks(author: String, genre: String): [Book!]!
    allAuthors: [Author!]!
    findAuthor(name: String!): Author
}

type Mutation {
    createUser(username: String!, favoriteGenre: String!, password: String!): User
    login(username: String!, password: String!): Token

    addBook(
      title: String!
      published: Int!
      author: String!
      genres: [String!]!
    ): Book
    addAuthor(
      name: String!
      born: Int
    ): Author
    editAuthor(name: String!, newName: String!): Author
    editBook(id: ID!, title: String, published: Int, author: String, genres: [String]): Book
}
